### ISSUE TITLE
Database.

### ISSUE THREAD

**Issue by RuslanMykhaylishyn** [premrishi/Angular-Spring-boot-Hospital-Management-System#1]
Hello, I wanted to use your site for a complete improvement, and I have a question: how can I make the database work? I haven't been able to figure this out all day :D. Waiting and thanks for the answer.

**Comment by premrishi** [comment]
Hi Ruslan, The backend and data base here should be deployed in different servers. There are 3 lambdas for backend. Appointment, demo, doclogin. Just pull those into a separate springboot project and run them separately either in your local or in cloud instance. And for database, i used mysql workbench. Create a table matching the backend with exact keys and values in mysql workbench and host it.
